export const TRANSITION_PAGE_START = 'TRANSITION_PAGE_START';
export const TRANSITION_PAGE_END = 'TRANSITION_PAGE_END';
export const RECEIVE_NOTIFICATION = 'RECEIVE_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
